directory: ${dir:src/main/resources/chartographer}
threads: 4
size:
  chartographer:
    width: 20000
    height: 50000
  fragment:
    width: 5000
    height: 5000

spring:
  liquibase:
    enabled: true
  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: h2
    password: 1
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: none
  h2:
    console:
      enabled: true
#    url: jdbc:postgresql://localhost:5432/kontur
#    username: postgres
#    password: 1
#    driver-class-name: org.postgresql.Driver
#    initialization-mode: always

logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
          sql:
          BasicBinder: TRACE

